---
# defaults file for haproxy_keepalived
minio_servers:
  - name: minio1
    ip: 172.16.16.101
  - name: minio2
    ip: 172.16.16.102
  - name: minio3
    ip: 172.16.16.103
  - name: minio4
    ip: 172.16.16.104
proxy1: 172.16.16.51
proxy2: 172.16.16.52    