---
- name: Set fact for minio download url
  set_fact:
    _server_url: "https://dl.min.io/server/minio/release/linux-amd64/minio-20241218131544.0.0-1.x86_64.rpm"

- name: Set fact checksum
  set_fact:
    _server_checksum: "https://dl.min.io/server/minio/release/linux-amd64/minio-20241218131544.0.0-1.x86_64.rpm.sha256sum"

- name: minio group
  group:
    name: "{{ minio_group }}"
    state: present

- name: minio user
  user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    system: "yes"
    shell: "/usr/sbin/nologin"

- name: Create the Minio config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0750
  with_items:
    - "{{ minio_etc_dir }}"
    - "{{ minio_cert_dir }}"
    - "{{ minio_policy_dir }}"

- name: Create the Minio data storage directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0750
  when: minio_server_make_datadirs
  with_items: "{{ minio_server_datadirs }}"

# - name: Install the minio server
#   yum:
#     name: "{{ _server_url }}"
#     disable_gpg_check: true
#     state: present
#   notify: Restart minio

- name: Generate the Minio server envfile
  template:
    src: minio.env.j2
    dest: "{{ minio_server_envfile }}"
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0640
  notify: Restart minio

- name: Create the Minio server systemd config
  template:
    src: minio.service.j2
    dest: "/etc/systemd/system/minio.service"
    owner: "root"
    group: "root"
    mode: 0644
  notify:
    - Reload minio systemd
    - Restart minio

- name: Ensure minio is started at boot
  service:
    name: minio
    enabled: true

- name: Update /etc/hosts
  become: true
  blockinfile:
      path: /etc/hosts
      create: yes
      block: |
        {% for item in groups['minio-nodes'] %}
        {{ hostvars[item].ansible_host }}    {{ item }}.cloudnativeapps.in    
        {% endfor %}

- name: Load tls key and cert from files
  set_fact:
    minio_key: "{{ lookup('file','/tmp/ssl/keys/cloudnativeapps.in.key') }}"
    minio_cert: "{{ lookup('file','/tmp/ssl/certs/cloudnativeapps.in.crt') }}"

- name: Copy SSL private key file
  copy:
    dest: "{{ minio_cert_dir }}/private.key"
    content: "{{ minio_key }}"
    owner: "{{ minio_user }}"
    group: "{{ minio_user }}"
    mode: 0644
  become: true
  when: minio_enable_tls
  notify: Restart minio

- name: Copy cert file
  copy:
    dest: "{{ minio_cert_dir }}/public.crt"
    content: "{{ minio_cert }}"
    owner: "{{ minio_user }}"
    group: "{{ minio_user }}"
    mode: 0644
  become: true
  when: minio_enable_tls
  notify: Restart minio